set_property SRC_FILE_INFO {cfile:/home/incolore/corewave/vivado/cpu/cpu.srcs/constrs_1/new/fpga_pins.xdc rfile:../../../cpu.srcs/constrs_1/new/fpga_pins.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC19 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y3 [get_ports rst]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H7 [get_ports led]
